### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [majormalfunk/pruner#2]
# Katselmointi

### Mitä tein

- Rekisteröidyin ja kirjauduin sisään
- Muokkasin profiilitietoja
- Lisäsin uuden tapahtuman (create new event) ja muokkasin sen tietoja
- Menin lisäämään uutta suunnitelmaa (make a new plan)

### Kokemus

- Sovellusidea kuulostaa mielekkäältä, toteutettu toiminallisuus toimii ja sovelluksen käyttö on pääosin helppoa
- Etusivun klikattavat "toimintolaatikot" on siisti idea
- Todella kätevää, että rekisteröitymisen jälkeen käyttäjä kirjautuu automaattisesti sisään
- Suunnitelman tekoon tarkoitettu käyttöliittymä on näppärä, mutta valitut vaihtoehdot eivät vaikuta tallentuvan
- Keskeneräistä toiminallisuutta löytyy aika paljon, jonka vuoksi käyttäjänä on vaikea hahmottaa, mitä sovelluksella oikeasti voi tällä hetkellä tehdä

## Koodi

- Frontti-koodilla erittäin selkeä rakenne, hyvä!
- Frontti-puolen reitityksessä kannattaisi käyttää esim. [react-router](https://reacttraining.com/react-router/core/guides/quick-start)-kirjastoa. Tällä hetkellä tieto millä sivulla käyttäjä on reduxissa, eikä osoiterivin polussa. Tästä seuraa ongelmia, jos käyttäjä päivittää sivun, haluaa siirtyä historiassa eteen- tai taaksepäin, tai lisätä esim. bookmarkin johonkin tapahtumaan
- Backend-puolella resolverit ja tyyppimääritellyt on ryhmitelty järkevästi, mainiota! Tosin, tyyppimäärittelyjen exporteissa on turhaan objekti jossa on pelkkä `typeDef`-avain (esimerkiksi [täällä](https://github.com/majormalfunk/pruner/blob/master/backend/graphql/user/typeDefUser.js#L3)) ja samoin resolvereissa (esimerkiksi [täällä](https://github.com/majormalfunk/pruner/blob/master/backend/graphql/user/resolverUser.js)). Exportin voisi kirjoittaa vain suoraan `module.exports = gql...`

## Kokonaisuus

- Sovelluksen idea on hyvä ja toteutettu toiminallisuus toimii pääosin moitteettomasti
- Keskeneräinen toiminallisuus vie huomiota käyttökelpoiselta toiminallisuudelta
- Frontti-puolella koodi on pääosin selkeää, mutta sivusiirtymissä voisi käyttää esim. react-router-kirjastoa redux:in sijaan

**Comment by majormalfunk** [comment]
Kiitos palautteesta!
